# Generated by Django 5.1 on 2025-01-04 17:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('account_type', models.CharField(choices=[('v', 'Vendor'), ('s', 'Self')], default='v', max_length=1)),
                ('details', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('Expenses', [('he', 'Home Expenses'), ('gr', 'Grocery'), ('hi', 'Home Improvement'), ('ph', 'Phone'), ('ut', 'Utilities'), ('in', 'Internet'), ('fa', 'Clothing, Fashion and Accessories'), ('fb', 'Food and Beverages'), ('lq', 'Liquor'), ('cr', 'Car and Vehicles'), ('me', 'Medical'), ('en', 'Entertainment'), ('tr', 'Travel'), ('cc', 'Child Care'), ('ed', 'Education'), ('sp', 'Support Payment'), ('ar', 'Short Term Lending'), ('gi', 'Gift and Charity'), ('or', 'Other Expenses')]), ('Income', [('sa', 'Salary & Wages'), ('go', 'Government Support'), ('bu', 'Business Income'), ('oi', 'Other Income')])], default='gr', max_length=2)),
                ('breakdown_option', models.CharField(choices=[('no', 'None'), ('mm', 'Multiple Months'), ('my', 'Multiple Years')], default='no', max_length=2)),
                ('start_date', models.DateField(default=datetime.datetime.today)),
                ('number_month', models.PositiveIntegerField(default=1)),
                ('number_year', models.PositiveIntegerField(default=1)),
                ('tfrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tfrom', to='myfinance.account')),
                ('tto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tto', to='myfinance.account')),
            ],
        ),
    ]
