# Generated by Django 5.1 on 2025-02-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0004_transaction_comment_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='track',
            field=models.BooleanField(default=False),
        ),
    ]
