# Generated by Django 4.2 on 2025-03-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0010_transaction_categorys_transaction_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(choices=[('I', 'Income'), ('E', 'Expenses'), ('T', 'Transfer')], default='I', max_length=1),
        ),
    ]
