# Generated by Django 5.1.6 on 2025-10-15 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='option',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
